# Generated by Django 6.0.5 on 2026-06-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_watchedmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedseason',
            name='tmdb_id',
            field=models.IntegerField(),
        ),
    ]
