# Generated by Django 6.0.5 on 2026-06-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_watchedseason_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedepisode',
            name='tmdb_id',
            field=models.PositiveIntegerField(),
        ),
    ]
