# Generated by Django 6.0.5 on 2026-06-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontent',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
