# Generated by Django 6.0.5 on 2026-07-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_favorites_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontent',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
