# Generated by Django 6.0.5 on 2026-07-01 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_usercontent_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontent',
            name='genres',
        ),
    ]
