# Generated by Django 6.0.5 on 2026-07-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_usercontent_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='favorites',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rating',
            name='media_type',
            field=models.CharField(default='movie', max_length=10),
        ),
        migrations.AddField(
            model_name='rating',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rating',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
